# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

docker-base: &docker-base
  host: localhost
  username: postgres
  password: postgres
  port: 12001

development:
  <<: [*default, *docker-base]
  database: cable_chatter

test:
  <<: [*default, *docker-base]
  database: cable_chatter_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
